---

- name: Install dependencies
  apt: pkg=python-pip
  when: ansible_os_family == 'Debian'

- name: Install supervisor
  pip: name=supervisor version={{ supervisor_version }}
  notify:
    - supervisor restart
    
- name: Install superlance
  pip: name=superlance
  when: supervisor_superlance

- name: Prepare directories
  file: state=directory path={{item}}
  with_items:
    - "{{supervisor_cfgdir}}"
    - "{{supervisor_logdir}}"
    - "{{supervisor_incdir}}"

- name: Configure supervisor - pt. 1
  template: src=supervisord.conf.j2 dest={{supervisor_conf_file}} owner=root group=root mode=0644
  notify:
    - supervisor restart

- name: Configure supervisor (Ubuntu) - pt. 2
  template: src=supervisor.conf.j2 dest=/etc/init/supervisor.conf owner=root group=root mode=0755
  when: ansible_distribution == 'Ubuntu'

- name: Configure supervisor (Debian) - pt. 2
  template: src=supervisor_debian.conf.j2 dest=/etc/init.d/supervisor owner=root group=root mode=0755
  when: ansible_distribution == 'Debian'

- name: Enable supervisor service (Debian) - pt. 3
  service: name=supervisor enabled=yes
  when: ansible_distribution == 'Debian'

- name: Ensure the supervisor is started
  service: name=supervisor state=started
